backend:
  name: git-gateway
  branch: main

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "news"
    label: "Nyheter"
    folder: "news"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Datum", name: "date", widget: "datetime" }
      - { label: "Beskrivning", name: "description", widget: "text" }
      - { label: "Innehåll", name: "body", widget: "markdown" }
